# Planning a Drone Mapping Campaign

by Andy Lyons, Shane Feirer, Becca Fenwick, and Sean Hogan

## Introduction

Imagine yourself the Director of a nature reserve. You get an email - an instructor of a field methods class at the local university is offering to send you a group of graduate students to  spend a week at your reserve to map the entire property with drones. That's an offer that's hard to pass up, but how do you even start to plan such a campaign? Mapping even a modest area with a single drone and a single pilot is a complicated workflow with a lot of moving parts. Coordinating multiple teams with multiple drones within a fix time frame adds even more complexity - particularly if you want to get good data!

This chapter offers some thoughts and suggestions for planning a drone campaign spanning multiple days and/or multiple flight teams. These lessons are based on our collective experiences including two campaigns to map >2000 acres of the Hopland Research and Extension Center, a xxx acre reserve in Mendicino County, California, most of which is extremely hilly oak woodland.

## Staffing Rules of Thumb

When thinking about how many people you'll need (or conversely how many flight teams you can support), a general rule of thumb is to allocate a minimum of **two people per drone**. 

At least one of person in each flight team needs to be an experienced drone pilot who holds a **FAA Part 107 Remote Pilot** license and is familiar with the equipment. In addition, each pilot will need at least one assistant to help with the many other tasks during fieldwork: packing and unpacking equipment, helping with launch and landing, keeping an eye open for any hazards in the air or on the ground, transferring and checking data, dealing with onlookers, etc. 

In theory a single pilot could perform all the tasks themselves, but you want your pilot to not be frazzled so they can focus on what they do best: mission planning, controlling the flight, monitoring equipment status, and thinking about the overall safety environment. 

If the assistant(s) are **novices**, having **two assistants per flight team** would be wise, at least for the first couple days of the campaign. If multiple teams are operating from a single launch site, you might be able to share an assistant across flights, but only if they're fairly experienced and physically fit!

It goes without saying that communication within a flight team is critical, and each team should do some practice flights *before* you're actually collecting the research data. Two-way radios are frequently helpful particularly if someone needs to deploy GCPs or you need to walk to the launch location.

If you have the luxury of enough people, it can be helpful to appoint the most experienced person to be the **overall coordinator**. This person should under-occupied with flight responsibilities so they can keep an eye on what's coming up next, make sure important steps have not been forgotten, help troubleshoot technical issues, answer questions, keep an eye on the weather and the time, etc. The more moving parts you have in your field logistics, the more important it is to have someone in a coordinator role.

Another role you may want to consider delegating is **collecting media material**. These are your drone video shots, photos of the drones and flight crews, 360 panoramas, etc. Field assistants can perform these roles if they have the right experience, but be wary of asking your pilots to use the research drones to take media shots. Drone mapping and videography are often different skillsets and there's more than enough to deal with just managing mapping missions.

## Planning Schedule

### 2-3 months before the campaign

Planning any kind of drone mapping project starts with a clear articulation of 1) the **science questions**, and 2) **data requirements** (e.g., what kind of imagery is needed - RGB, multispectral, or thermal? How about the spatial resolution, geographic area of interest, spatial accuracy, time of day). Check in with the research scientist(s) and/or land managers for clarification. If no one can articulate these basic requirements, consider that a **yellow flag** that you may be heading down the path of collecting data for the sake of collecting data! Rethink the project, or put it on hold until you're sure there's actually a need for the data.

2-3 months out is also when you want to assess **regulatory requirements**. If needed, start the process to apply for **FAA ATC clearance** or **Part 107 waviers**. Contact the **land manager** and start any permit processes required. Don't forget about contacting neighboring land owners, whose consent may not be strictly required but could prevent all manner of delays and disruptions to the project.

You also want to inventory your **equipment**. Don't forget [accessories](#accessories) including enough batteries, memory cards, spare propellors, launch pads, field tables, pop-up shade structures, power supplies, cables, radios, first aid kit, fire extinguishers, water sprayers, etc. Give yourself enough time to order anything that's needed.

### 2-4 weeks before the campaign

Fine-tune the fieldwork logistics by doing a **reconnaissance of the area**. Identify launch sites, flight areas, travel times, etc. Finalize your estimate of the number of days / people / vehicles needed.

Prepare everything you need for the crew **training and orientation sessions**. These include printed maps of the project area with launch sites marked out, printed copies of any permits needed, phone numbers, equipment user guides, checklists, etc. 

And don't forget your digital resources, which could include KMLs for the flight planning software, custom basemaps for Avenza Maps, soft copies of users guides, etc.

### 1-week before the campaign

**Training**. If possible, do your **test flights** and **training** with the field teams a week before the actual campaign. You want the trial and learning period to be *before* the campaign so it is low-stress and the pressure of meeting a actual data collection schedule isn't pushing people to do things beyond their skill level. 

Training the flight teams before the campaign starts will also give you a buffer to deal with equipment issues, evaluate if your campaign schedule is realistic, collect and process some sample data, tweak the parameters of your mission plans, and give your flight teams a chance to work together. You want your people to make mistakes during training, not the actual data collection.

> You want your people to make mistakes during training,You want your people to make mistakes during training, not the actual data collection, not the actual data collection.

Don't forget to practice **responding to the unexpected**. For example, if the drone lands off-target, or even worse drops out of the sky 1000 feet away, how are you going to organize a search and rescue operation? Practice loss of connection scenarios, test that your obstacle avoidance features actually work, etc. Even experienced pilots will benefit from this kind of refresher.

If it isn't possible to hold training and orientation prior to the campaign, plan on spending at least half of the first day on instruction, and at least half of the second day going over the data and debriefing the field work. You may not get as much research data collected those first two days, but by investing the time in instruction and reflection you'll be well on your way to a smooth and efficient operation.

**Weather**. Check the 10-day weather forecast

## Week of the Campaign

### Day-to-day Schedule

Many of us are used to waking up early during fieldwork, heading out to the site as quickly as possible, spending as much time as we can collecting data, returning to base when the sun goes down or our energy is depleted, having dinner, sleeping, waking up, and repeating.

However spending dawn-to-dusk in the field is a poor strategy for drone mapping. Shadows in the early morning and late afternoon can ruin data, so in most cases you really only want to fly a couple of hours before and after solar noon. However equally important, you need to allocate time to review and organize your data, and attend to the myriad tasks that come before and after flights.

After each day of flying, expect to spend **2-4 hours** copying and organizing the images into directories, downloading flight logs from your drones and GPS devices, typing up notes, post-processing data with your flight management software, creating metadata, doing some preliminary stitching for quality control, and refining the flight plans for the following day. Then there will also be a host of equipment tasks - dusting off lenses and engines, reformatting memory cards, recharging batteries, cleaning vehicles, etc. If the day didn't go great, you'll probably want to have a meeting with the flight team to process lessons learned and come up with a strategy to improve operations tomorrow.

If it isn't practical to work an additional 2-4 more hours at the end of each day in the field, then schedule an office day between flight days, or just plan on only spending 1/2 of each day flying. You may of course try to cram in as many flights per day, but at the risk of collecting data that doesn't stitch well, has gaps, or takes many extra hours of manual steps during processing. 

